#!/usr/bin/env python3
"""Preserve hand-edited thumbnails across script runs.

`gen_og_images.py` and `publish_country.py` regenerate thumbnails from the source
photos. If you hand-edit an output (a custom crop of a dest-card or OG image), a
later regeneration would silently overwrite it. To prevent that, those scripts
record the hash of every thumbnail THEY generate in `tools/.thumb-manifest.json`.
Before overwriting, they call `is_manual(path)`: if the file on disk differs from
the hash we last generated (or was never generated by us), it's treated as a
manual edit and skipped. `--force` on either script bypasses this.

So: edit a thumbnail by hand, and it just sticks. To hand back control of a file,
delete its entry from the manifest (or re-run with --force).
"""
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "tools", ".thumb-manifest.json")


def _rel(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def _hash(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def _load():
    try:
        return json.load(open(MANIFEST, encoding="utf-8"))
    except (FileNotFoundError, ValueError):
        return {}


def is_manual(path):
    """True if a thumbnail exists on disk but no longer matches the version we last
    generated (i.e. it was hand-edited) — callers must NOT overwrite it."""
    if not os.path.exists(path):
        return False
    rec = _load().get(_rel(path))
    return rec is None or _hash(path) != rec


def record(path):
    """Record the hash of a thumbnail we just generated, so later hand-edits show up."""
    if not os.path.exists(path):
        return
    m = _load()
    m[_rel(path)] = _hash(path)
    json.dump(m, open(MANIFEST, "w", encoding="utf-8"), indent=0, sort_keys=True)
